Release
jarviscanada/jarvis_data_eng_HarsimranKaur pull request #4
Opened 2021-03-24 17:53 UTC by HarsimranKaur13

2021-03-24 18:03 UTC, jarviscanada requested changes
Fix all and open another PR

2021-03-24 18:03 UTC, jarviscanada commented on core_java/grep/.idea/compiler.xml
> +<project version="4">
git rm core_java/grep/.idea

2021-03-24 18:03 UTC, jarviscanada commented on core_java/grep/data/file1.txt
> +Cat is an animal
remove all test files

2021-03-24 18:03 UTC, jarviscanada commented on core_java/grep/dependency-reduced-pom.xml
> +  <groupId>ca.jrvs.apps</groupId>
remove this

2021-03-24 18:03 UTC, jarviscanada commented on core_java/grep/grep.iml
> +  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8">
remove this

2021-03-24 18:03 UTC, jarviscanada commented on core_java/grep/outFile
> +Text us later at night
remove

2021-03-24 18:03 UTC, jarviscanada commented on core_java/grep/target/maven-archiver/pom.properties
> +#Wed Mar 10 19:04:55 UTC 2021
git rm core_java/grep/target

2021-03-24 18:03 UTC, jarviscanada commented on linux_sql/linux.jpeg
> +<mxfile host="app.diagrams.net" modified="2021-03-24T15:45:37.851Z" agent="5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36" etag="WbhnyQaaULD
fix it

2021-03-24 18:03 UTC, jarviscanada commented on linux_sql/scripts/host_info.sh
> +('$hostname',1,'$cpu_architecture','$cpu_model',$cpu_mhz, $l2_cache, 1254, '$timestamp');"
remove

2021-03-24 18:03 UTC, jarviscanada commented on linux_sql/scripts/ddl.sql
> +    host_id SERIAL NOT NULL,
make it a FK

2021-03-24 18:03 UTC, jarviscanada commented on linux_sql/scripts/host_usage.sh
> +export PGPASSWORD=$psql_password
ID is missing

2021-03-24 18:03 UTC, jarviscanada commented on linux_sql/scripts/psql_docker.sh
> +  if [ -z "$2" ] || [ -z "$3" ] ;
don't use $1 instead, use vars

2021-03-24 18:03 UTC, jarviscanada commented on linux_sql/scripts/queries.sql
> +SELECT AVG(7492108-memory_free),timestamp FROM (SELECT memory_free,date_trunc('hour', timestamp) + date_part('minute', timestamp):: int / 5 * interval '5 min' as timestamp FROM host_usage) as ss
fix it

2021-03-29 13:53 UTC, HarsimranKaur13 commented on linux_sql/scripts/queries.sql
> +SELECT AVG(7492108-memory_free),timestamp FROM (SELECT memory_free,date_trunc('hour', timestamp) + date_part('minute', timestamp):: int / 5 * interval '5 min' as timestamp FROM host_usage) as ss
Done

2021-03-29 13:53 UTC, HarsimranKaur13 commented on linux_sql/scripts/psql_docker.sh
> +  if [ -z "$2" ] || [ -z "$3" ] ;
Done

2021-03-29 13:53 UTC, HarsimranKaur13 commented on linux_sql/scripts/host_usage.sh
> +export PGPASSWORD=$psql_password
ID type is SERIAL, hence it gets added automatically.

2021-03-29 13:54 UTC, HarsimranKaur13 commented on linux_sql/scripts/ddl.sql
> +    host_id SERIAL NOT NULL,
Done

2021-03-29 13:54 UTC, HarsimranKaur13 commented on linux_sql/scripts/host_info.sh
> +('$hostname',1,'$cpu_architecture','$cpu_model',$cpu_mhz, $l2_cache, 1254, '$timestamp');"
Removed

2021-03-29 13:55 UTC, HarsimranKaur13 commented on core_java/grep/outFile
> +Text us later at night
Removed core_java from the develop branch as of now.

2021-03-29 13:55 UTC, HarsimranKaur13 commented on core_java/grep/grep.iml
> +  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8">
Removed core_java from the develop branch as of now.

2021-03-29 13:55 UTC, HarsimranKaur13 commented on core_java/grep/dependency-reduced-pom.xml
> +  <groupId>ca.jrvs.apps</groupId>
Removed core_java from the develop branch as of now.

2021-03-29 13:55 UTC, HarsimranKaur13 commented on core_java/grep/data/file1.txt
> +Cat is an animal
Removed core_java from the develop branch as of now.

2021-03-29 13:55 UTC, HarsimranKaur13 commented on core_java/grep/.idea/compiler.xml
> +<project version="4">
Removed core_java from the develop branch as of now.

2021-03-30 00:19 UTC, jarviscanada approved these changes
please merge

2021-03-30 00:19 UTC, jarviscanada commented on jarvis_data_eng_Projects.iml
> +    <exclude-output />
remove

2021-03-31 05:02 UTC, merged